// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231218172623_NewMigration2")]
    partial class NewMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Models.Bird", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("CanFly")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Birds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c38239de-4ff1-467d-9f87-9e2fe1818465"),
                            CanFly = false,
                            Name = "Drake"
                        },
                        new
                        {
                            Id = new Guid("21e2cb9a-c71e-49f7-af64-3e9f38f3ccaf"),
                            CanFly = false,
                            Name = "Simon"
                        },
                        new
                        {
                            Id = new Guid("6b7e2976-1004-4cdc-8c09-b21131846a0a"),
                            CanFly = false,
                            Name = "Gustav"
                        });
                });

            modelBuilder.Entity("Domain.Models.Cat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("LikesToPlay")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("446a0d4c-0a54-4e16-b812-c712ae312de9"),
                            LikesToPlay = false,
                            Name = "Nemo"
                        },
                        new
                        {
                            Id = new Guid("91094fb7-1176-4a2f-9b2b-2b0d9a1fdc46"),
                            LikesToPlay = false,
                            Name = "Doris"
                        },
                        new
                        {
                            Id = new Guid("b810711b-69d9-4388-baf8-25099da34d6d"),
                            LikesToPlay = false,
                            Name = "Simba"
                        });
                });

            modelBuilder.Entity("Domain.Models.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("884fc3b6-7fd1-4851-ad44-62b1196ab8ac"),
                            Name = "Björn"
                        },
                        new
                        {
                            Id = new Guid("6f18bd58-efe4-4882-8161-c22b71e404c2"),
                            Name = "Patrik"
                        },
                        new
                        {
                            Id = new Guid("10f13ad9-0f72-4206-b626-783d0b95c1ea"),
                            Name = "Alfred"
                        });
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
