// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231208013605_SeedDataMigration")]
    partial class SeedDataMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Models.Bird", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("CanFly")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Birds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c592b78-10fb-4f31-b925-bc0a60794306"),
                            CanFly = false,
                            Name = "Drake"
                        },
                        new
                        {
                            Id = new Guid("9f9242f8-f6f9-403d-81be-57f15801a47f"),
                            CanFly = false,
                            Name = "Simon"
                        },
                        new
                        {
                            Id = new Guid("6ac0f273-92b1-4d4e-b5cb-c0474279d697"),
                            CanFly = false,
                            Name = "Gustav"
                        });
                });

            modelBuilder.Entity("Domain.Models.Cat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("LikesToPlay")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7211c09c-6268-43bd-b72d-612298ee9026"),
                            LikesToPlay = false,
                            Name = "Nemo"
                        },
                        new
                        {
                            Id = new Guid("814b2e91-7e7d-435d-9a9d-8c83e8bc7da9"),
                            LikesToPlay = false,
                            Name = "Doris"
                        },
                        new
                        {
                            Id = new Guid("7245cfb3-2071-4143-b8f2-3b131bd405f4"),
                            LikesToPlay = false,
                            Name = "Simba"
                        });
                });

            modelBuilder.Entity("Domain.Models.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e54bae7-d7d0-4382-96e6-911db1157514"),
                            Name = "Björn"
                        },
                        new
                        {
                            Id = new Guid("7041c8d9-aa88-4e71-9ce6-422092c52b58"),
                            Name = "Patrik"
                        },
                        new
                        {
                            Id = new Guid("7f957594-dc3d-491a-b21f-dcae12b314e9"),
                            Name = "Alfred"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
