// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231218172120_NewMigration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Models.Bird", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("CanFly")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Birds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a30a64d7-553f-4a8e-9617-8a70d5464cdb"),
                            CanFly = false,
                            Name = "Drake"
                        },
                        new
                        {
                            Id = new Guid("1ab23ee7-de9e-4fe0-aaa9-0b3f8a580d19"),
                            CanFly = false,
                            Name = "Simon"
                        },
                        new
                        {
                            Id = new Guid("b05cf71b-68a3-4515-b9d3-5b5b82026c6c"),
                            CanFly = false,
                            Name = "Gustav"
                        });
                });

            modelBuilder.Entity("Domain.Models.Cat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("LikesToPlay")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24703e2b-2c40-493a-aa8c-dff44f4bc2e1"),
                            LikesToPlay = false,
                            Name = "Nemo"
                        },
                        new
                        {
                            Id = new Guid("a872f013-48d7-4242-b6d1-45f01b2f5a15"),
                            LikesToPlay = false,
                            Name = "Doris"
                        },
                        new
                        {
                            Id = new Guid("4c1ee71a-22d4-483e-a471-092f1b334560"),
                            LikesToPlay = false,
                            Name = "Simba"
                        });
                });

            modelBuilder.Entity("Domain.Models.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("79d17d29-03d6-4b4a-8ece-c557e257f36b"),
                            Name = "Björn"
                        },
                        new
                        {
                            Id = new Guid("f0e1b9a9-8f1d-40e6-bcdb-529ea5b7acae"),
                            Name = "Patrik"
                        },
                        new
                        {
                            Id = new Guid("3184fa5e-ff22-449a-893b-f1a500a136a6"),
                            Name = "Alfred"
                        });
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
