// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Models.Animal.AnimalModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AnimalModel");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AnimalModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Models.UserAnimal", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AnimalModelId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "AnimalModelId");

                    b.HasIndex("AnimalModelId");

                    b.ToTable("UserAnimals");
                });

            modelBuilder.Entity("Domain.Models.Bird", b =>
                {
                    b.HasBaseType("Domain.Models.Animal.AnimalModel");

                    b.Property<bool>("CanFly")
                        .HasColumnType("tinyint(1)");

                    b.HasDiscriminator().HasValue("Bird");

                    b.HasData(
                        new
                        {
                            Id = new Guid("902ce39e-ad27-4aea-84ee-9829c80a5957"),
                            Name = "Drake",
                            CanFly = false
                        },
                        new
                        {
                            Id = new Guid("8ae07781-1c2c-40a1-89bf-7d7832dd6095"),
                            Name = "Simon",
                            CanFly = false
                        },
                        new
                        {
                            Id = new Guid("22f1b863-a4fa-46a2-b637-0e46aa14de6e"),
                            Name = "Gustav",
                            CanFly = false
                        });
                });

            modelBuilder.Entity("Domain.Models.Cat", b =>
                {
                    b.HasBaseType("Domain.Models.Animal.AnimalModel");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LikesToPlay")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Cat");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b566961d-d570-487e-ba51-fe718c9336b1"),
                            Name = "Nemo",
                            Breed = "Siamese",
                            LikesToPlay = false,
                            Weight = 6
                        },
                        new
                        {
                            Id = new Guid("a76dbfb5-71c0-4995-b956-343327c36053"),
                            Name = "Doris",
                            Breed = "Persian",
                            LikesToPlay = false,
                            Weight = 5
                        },
                        new
                        {
                            Id = new Guid("d85bfc26-ab97-4a31-a96f-5291a2ffd7b4"),
                            Name = "Simba",
                            Breed = "BondeKatt",
                            LikesToPlay = false,
                            Weight = 10
                        });
                });

            modelBuilder.Entity("Domain.Models.Dog", b =>
                {
                    b.HasBaseType("Domain.Models.Animal.AnimalModel");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.ToTable("AnimalModel", t =>
                        {
                            t.Property("Breed")
                                .HasColumnName("Dog_Breed");

                            t.Property("Weight")
                                .HasColumnName("Dog_Weight");
                        });

                    b.HasDiscriminator().HasValue("Dog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8fe661c4-68e3-4d7c-a500-a3429494e88f"),
                            Name = "Björn",
                            Breed = "Labrador",
                            Weight = 20
                        },
                        new
                        {
                            Id = new Guid("50c6d480-e2f1-4951-87ad-380886414108"),
                            Name = "Patrik",
                            Breed = "Golden Retriver",
                            Weight = 50
                        },
                        new
                        {
                            Id = new Guid("9a270fa1-eab5-4463-8ced-5db94d130620"),
                            Name = "Alfred",
                            Breed = "Beagle",
                            Weight = 15
                        });
                });

            modelBuilder.Entity("Domain.Models.UserAnimal", b =>
                {
                    b.HasOne("Domain.Models.Animal.AnimalModel", "AnimalModel")
                        .WithMany("UserAnimals")
                        .HasForeignKey("AnimalModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("UserAnimals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalModel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Animal.AnimalModel", b =>
                {
                    b.Navigation("UserAnimals");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Navigation("UserAnimals");
                });
#pragma warning restore 612, 618
        }
    }
}
